// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhznuRkYk1pVMpkF-MqNbAeSvO9NuWrVo',
    appId: '1:714419254384:web:b618a849e658bf722770b5',
    messagingSenderId: '714419254384',
    projectId: 'bcdx-11312136',
    authDomain: 'bcdx-11312136.firebaseapp.com',
    storageBucket: 'bcdx-11312136.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG7vLRAipekO9ec-5FQiBCXMpOfIC5ppo',
    appId: '1:714419254384:android:58e8fa5bdb245d212770b5',
    messagingSenderId: '714419254384',
    projectId: 'bcdx-11312136',
    storageBucket: 'bcdx-11312136.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANzcu2DPr2hEf_zn9LuQNq6geQgur1A00',
    appId: '1:714419254384:ios:f043ba8dde416d172770b5',
    messagingSenderId: '714419254384',
    projectId: 'bcdx-11312136',
    storageBucket: 'bcdx-11312136.appspot.com',
    iosBundleId: 'com.example.bcdx11312136',
  );
}
